# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shift-left-test-engine
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: engine=localhost:5000/shift-left-test-engine
    argocd-image-updater.argoproj.io/engine.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: 'https://github.com/Yugikratos/shift-left-test-engine.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: data-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
