CREATE MULTISET TABLE fin_core.business_credit_score ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      BUS_NBR CHAR(9) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      EFF_STRT_DT DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      ROW_TYP_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ROW_VER_NBR CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      EFF_END_DT DATE FORMAT 'YYYY-MM-DD',
      CR_SCOR_RISK_CLSS_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      CR_RISK_PCT DECIMAL(3,0),
      CR_RISK_PT_VAL CHAR(3) CHARACTER SET LATIN NOT CASESPECIFIC,
      FINC_STRSS_SCOR_CD CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      FINC_PCT DECIMAL(3,0),
      FINC_STRSS_RAW_SCOR CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC,
      LOGC_DEL_IND CHAR(1) CHARACTER SET LATIN NOT CASESPECIFIC,
      DW_LOAD_PUBL_ID INTEGER,
      DW_UPDT_PUBL_ID INTEGER,
      VIABL_RT CHAR(4) CHARACTER SET LATIN NOT CASESPECIFIC)
UNIQUE PRIMARY INDEX BUS_CREDIT_SCORE_PK ( BUS_NBR ,EFF_STRT_DT );
