CREATE MULTISET TABLE fin_ctl.etl_cyc_ctl ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      ETL_CYC_DT DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      ETL_PROC_CD CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_CYC_STRT_TS TIMESTAMP(6),
      ETL_CYC_END_TS TIMESTAMP(6),
      ETL_CYC_FREQ_CD VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      ETL_CYC_STS_CD VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      ETL_CYC_ID BIGINT)
UNIQUE PRIMARY INDEX ETL_CYC_CTL_PK ( ETL_CYC_DT ,ETL_PROC_CD );

CREATE MULTISET TABLE fin_ctl.etl_src_ctl ,FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT
     (
      ETL_CYC_DT DATE FORMAT 'YYYY-MM-DD' NOT NULL,
      ETL_PROC_CD CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      SRC_CD CHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_REC_CNT INTEGER,
      CTL_REC_CNT INTEGER,
      ETL_SRC_STRT_TS TIMESTAMP(6),
      ETL_SRC_END_TS TIMESTAMP(6),
      ETL_SRC_STS_CD CHAR(5) CHARACTER SET LATIN NOT CASESPECIFIC,
      ETL_SRC_STS_RSN_CD VARCHAR(20) CHARACTER SET LATIN NOT CASESPECIFIC,
      ETL_SRC_FILE_CHKUM_TXT VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRC_CYC_DT DATE FORMAT 'YYYY-MM-DD',
      SRC_FILE_NM VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      SRC_CTL_FILE_NM VARCHAR(100) CHARACTER SET LATIN NOT CASESPECIFIC,
      DW_PUBTN_SRC_CD CHAR(2) CHARACTER SET LATIN NOT CASESPECIFIC NOT NULL,
      ETL_CYC_ID BIGINT)
UNIQUE PRIMARY INDEX ETL_SRC_CTL_PK ( ETL_CYC_DT ,ETL_PROC_CD ,SRC_CD );
